### PR TITLE
Dingpf/spack release

### PR DESCRIPTION
**Pull request by dingp**
## This PR brings in the package.py files in [proto-spack](https://github.com/DUNE-DAQ/proto-spack)

Additionally, it address the following issues:
1. https://github.com/DUNE-DAQ/proto-spack/issues/9
2. https://github.com/DUNE-DAQ/proto-spack/issues/10
3. https://github.com/DUNE-DAQ/proto-spack/issues/8
4. https://github.com/DUNE-DAQ/proto-spack/issues/7

## Noticeable changes of spack packages:
1. `dune_daqpackages` is now changed to `dunedaq`;
2. umbrella packages `systems`, `devtools`, `externals` have been moved to the release specific repo (the package.py template directory under `daq-release/spack-repo/packages`;
3. `package.py` file for all packages under `proto-spack/dune_daqpackages` have been converted into templates;
5. added `package.py` template for `dtpcontrols, uhallibs, rawdatautils`;
6. provided a script (`make-release-repo.py`) to generate release specific repos from the templates, and provided option obtaining commit hashes of `develop` head or a tag.
7. added YAML file defining the release, used by the python script above to generate the spack repo. This is done for `dunedaq-develop` at `daq-release/configs/dunedaq-develop/dunedaq-develop.yaml`, and for `dunedaq-v2.10.1` at `daq-release/configs/dunedaq-v2.10.1/dunedaq-v2.10.1.yaml`.

## Here are the instructions of generating spack repos with the `make-release-repo.py`.

The following combination of commands will generate a release repo under `test-repo-outidr` for `dunedaq-v2.10.1`.
```bash
git clone http://github.com/DUNE-DAQ/daq-release -b dingpf/spack-release
cd daq-release/scripts/spack/
./make-release-repo.py -t ../../spack-repos/release-repo-template -i ../../configs/dunedaq-v2.10.1/dunedaq-v2.10.1.yaml -o ./test-repo-outdir
```

Calling the script in the following way will generate a release repo for the nightly release `N22-03-30` (as of today).
```
./make-release-repo.py -t ../../spack-repos/release-repo-template -i ../../configs/dunedaq-develop/dunedaq-develop.yaml -u -o ./test-nightly -r N22-03-30
```

Documentations will be added in `daq-release/docs` once the tool becomes more mature and tested.

### CODE REVIEW

**Comment by dingp** [comment]
A few important fixes to some external package versions, and dependencies to make this happen:

* spack package `krb5` is added as a dependency to `dqm` and `kafkaopmon`, without this change, the package will look for system `krb5-libs`, which likely depends on a different `openssl` version than the currently loaded on in spack;
* `pugixml` is added as a `run` dependency for `uhal`. It was only `build` dependency before, and caused linking errors when building `uhallibs`. The issue was not exposed in previous releases as `uhallibs`, which uses shared libs from `uhal`  with symbols of `pugixml`, was only introduced in this release.

**Comment by jcfreeman2** [comment]
Reviewer update: I've been able to successfully create a nightly release in a docker container following the instructions at https://github.com/DUNE-DAQ/daq-release/wiki/Preparing-the-deployment-of-DUNE-DAQ-spack-releases-to-cvmfs#making-a-spack-instance-for-a-single-nightly-release, but two quick points:
1) I needed to manually add a dependency on `utilities` to `ipm`'s `package.py` file
2) There are `package.py`s for obsolete packages which probably don't need Spack support - `readout`, e.g.

**Comment by jcfreeman2** [comment]
Things look like they're in good shape. 

I followed the instructions in https://github.com/DUNE-DAQ/daq-release/wiki/Preparing-the-deployment-of-DUNE-DAQ-spack-releases-to-cvmfs#prepare-the-prebuilt-python-virtual-environment-dbt-pyvenv-for-a-release to create a python environment, to add to the `dunedaq@N22-04-13` Spack package I made yesterday. Pengfei copied my output into `/cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/N22-04-13`, and using the head of the `johnfreeman/issue161_spack` branch of daq-buildtools (`c2d8cfa646b4be`) I was able to create a work area based on the nightly I created and build appfwk (`/nfs/sw/work_dirs/jcfree/spack-work/daqbuild_N22-04-13_spack`).

**Comment by dingp** [comment]
Thanks @jcfreeman2 

I am merging the branch now.

**Pull request merged**
