### PR TITLE
JCF: Issue #155: apply patches to ensure all trace elements are insta…

### PR DESCRIPTION
**Pull request by jcfreeman2**
…lled

### CODE REVIEW

**Review by dingp — COMMENTED** [review]
`disable_cetmodules.diff` is not applicable any more on the `stable`  branch. It has moved with a newer `cetmodules` version. I suggest simply removing `stable` and `master` from the package.py file.

**Comment by jcfreeman2** [comment]
Right, that's what's done in the `package.py` with this PR - i.e., `stable` and `master` are removed. Or am I misunderstanding something?

**Comment by dingp** [comment]
Sorry, I overlooked the change late last night. 😅 I’ll try to reinstall trace and see if the issue goes away.

**Comment by dingp** [comment]
Installed `trace/q7kxpcj` in the `Spack-externals` instance.

It does have the `trace_functions.sh` and some other executables installed now.

**Pull request merged**
